### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by vincentmaule** [OptimisticShaggy/LAB-101-misc-markdown#1]
## Write a blog article about a computer skill you recently learned

@egillespie Can you take a look at this? It's [hosted here](https://OptimisticShaggy.github.io/LAB-101-misc-markdown/index.html) and meets the following criteria:

- [x] The skill is learned from a 45-minute or more video, podcast, or event
- [x] All blog content is in one Markdown file containing [at least 400 words](https://wordcounter.net)
- [x] The article uses complete sentences to explain what you learned, but it's okay if the spelling and grammar aren't perfect
- [x] The blog has at least two levels of headings and a link to the video, podcast, or event
- [x] At least five other types of Markdown notation are used that are not headings or links
- [x] The hosted site is generated with a built-in GitHub Pages theme
- [x] The article is viewable at the top level (`/`) of your hosted site

Emoji's are unable to show, any ideas?

**Comment by egillespie** [comment]
Your site looks slick and I like the use of reference links! 👌 Here's an explanation of the emoji and one extra request. Can you try these out?

### Emoji on websites

The reason the emoji aren't appearing on your website even though they do appear on GitHub is because your Markdown is using special placeholder text instead of actual emoji characters. For example, `:open_mouth:` instead of 😮 .

Emoji are actual characters that exist in a font, whereas placeholder text is plain characters using a special colon-delimited syntax that only GitHub and certain other sites support. Browsers don't recognize the placeholder syntax.

If you want the emoji to appear, I recommend using a site like [getemoji.com](http://getemoji.com) to find the emoji character, copy, and paste it into your document. That way it will appear on both GitHub and your hosted site.

### Creating an information hierarchy with headings

Immediately following your _Docker_ level-one heading (`#`), you have a few level-three (`###`) headings. In order to correctly establish an information hierarchy that screen readers, search engines, and other software will properly interpret, headings should always be one level deeper than their parent. Doing this correctly may also have presentation/style benefits as well, so it's not just helpful to marginalized people and bots.

Would you mind replacing the level-three headings immediately following your _Docker_ heading with level-two headings?

### Add a splash of other Markdown syntax

I like the Markdown you are using and it looks really nice. Would you mind flexing some other Markdown syntax in your site so I can see a more comprehensive understanding of the syntax from you? I think code blocks with `docker` commands might be a good one. Ditto with images. 2-3 more should be enough. 😉 

---

After you’ve made your changes and pushed them to GitHub and your hosted site, give it a once-over to make sure it looks right, then comment back here and I’ll take another look.

Thanks! 🤖

**Comment by vincentmaule** [comment]
I wanna add, it's really stupid about the Emojis...
Beyond this, I believe I was able to get everything added.

**Comment by egillespie** [comment]
Those emoji placeholders are yeah... not consistently supported. Unfortunately when companies create proprietary replacements for widely accepted and popular free standards, broad support is really inconsistent. 😕 

Your changes look nice. I like how the code snippets look and I can see the emoji in all the right places. Nice job! 🎉 :shipit:

**Comment by vincentmaule** [comment]
What I've learned from this project is Markdown, touching more on that skill which I thought was awesome. Especially considering Markdown is used in so many other places on the Internet.
